export const INITIAL_CATS = [
  {
    id: 'social',
    name: 'Social Media',
    color: '#1877f2',
    bg: '#eff4ff',
    border: '#d0e0fd',
    iconHTML: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><circle cx="8" cy="4" r="1.8"/><circle cx="2.5" cy="11.5" r="1.8"/><circle cx="13.5" cy="11.5" r="1.8"/><line x1="8" y1="5.8" x2="2.5" y2="9.7"/><line x1="8" y1="5.8" x2="13.5" y2="9.7"/></svg>',
    library: [
      'Plan de communication mensuel',
      'La gestion des reseaux sociaux',
      'La gestion de la communaute',
      'Web Analytics & KPIs',
      'Reunion Client (Reporting / Briefing)',
      'Copywriting',
      'Moderation de la page',
      'Strategie de contenu',
      'Audit des reseaux sociaux',
    ],
    selected: [],
  },
  {
    id: 'design',
    name: 'Conception Graphique',
    color: '#8b5cf6',
    bg: '#f5f0ff',
    border: '#ddd0fd',
    iconHTML: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><circle cx="8" cy="8" r="3"/><line x1="8" y1="1" x2="8" y2="3"/><line x1="8" y1="13" x2="8" y2="15"/><line x1="1" y1="8" x2="3" y2="8"/><line x1="13" y1="8" x2="15" y2="8"/></svg>',
    library: [
      'La creation des posts (graphic design, composition des photos)',
      'Habillage des reseaux sociaux',
      'Charte graphique',
      'Logo design',
      'Flyers et affiches',
      'Carte de visite',
      'Identite visuelle complete',
      'Banniere et couverture',
    ],
    selected: [],
  },
  {
    id: 'video',
    name: 'Videos & Prod',
    color: '#ef4444',
    bg: '#fff0f0',
    border: '#fdd0d0',
    iconHTML: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="1" y="4" width="10" height="8" rx="1.5"/><polyline points="11,6.5 15,4.5 15,11.5 11,9.5"/></svg>',
    library: [
      'Video making (shooting, editing, motion graphique sound design)',
      'Reels et Stories',
      'Shooting photo',
      'Motion graphic',
      'Teaser / Spot publicitaire',
      'Montage video',
      'Animation 2D',
      'Drone footage',
    ],
    selected: [],
  },
  {
    id: 'it',
    name: 'IT',
    color: '#10b981',
    bg: '#edfaf3',
    border: '#c0f0d8',
    iconHTML: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="1" y="2" width="14" height="10" rx="1.5"/><line x1="5" y1="15" x2="11" y2="15"/><line x1="8" y1="12" x2="8" y2="15"/></svg>',
    library: [
      'Creation de site web',
      'Application mobile',
      'Maintenance web',
      'SEO / Referencement',
      'SEA / Publicite en ligne',
      'E-commerce',
      'Refonte de site',
      'Securite et hebergement',
    ],
    selected: [],
  },
  {
    id: 'event',
    name: 'Evenementiel',
    color: '#f59e0b',
    bg: '#fffbeb',
    border: '#fde68a',
    iconHTML: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><rect x="1" y="3" width="14" height="12" rx="1.5"/><line x1="5" y1="1" x2="5" y2="5"/><line x1="11" y1="1" x2="11" y2="5"/><line x1="1" y1="7" x2="15" y2="7"/></svg>',
    library: [
      "Organisation d evenement",
      'Couverture evenementielle',
      'Live streaming',
      'Reportage photo et video',
      'Coordination logistique',
      'Decoration et scenographie',
      'Animation et MC',
      'Gestion des invitations',
    ],
    selected: [],
  },
];
